include::./constant.adoc[]

== Installation Details
:toc:

Please be careful in following the installation instructions to the letter. Otherwise, you may end up encountering a lot of issues in using these tools.

=== Installing on MS Windows Platform

==== [[install-jdk-win]] Installing {openjdk-cv}

We will use {openjdk-cv} to learn how to program enterprise application.

[arabic]
. Downlad {openjdk-cv-url}[OpenJDK version 11 (or, OpenJDK 11)] from {adoptium-url}[Adoptium]
+
[TIP]
====
. Check that the choosen platform for download is Windows

. Choose "Temurin 11 (LTS)"

. Select "Latest release"
====
+
[NOTE]
====
. Besides Eclipse's Temurin OpenJDK, there are other providers as well. I have not tried any of these. Hence, you may want to use your own OpenJDK provider, but at your own risk.

. Remember where you store the downloaded installation file.
====

:{openjdk-11-url}: https://adoptium.net/?variant=openjdk11&jvmVariant=hotspot
:{adoptium-url}: https://adoptium.net/

=== Installing on Mac OS X


=== Installing on Linux (to do)
